# random 

In [1]:
import random 

In [2]:
a= random.random()
print(a)

0.07108961555535254


val2= random.randint(1.10)
print(val2)

In [3]:
val2 = random.randint(1,19)
print(val2)

9


In [4]:
m= ['hii', 'hello', 'how r uh ?', 'i m fne uh say']
a=random.choice(m)
print(a)

hello


In [5]:
m= ['hii', 'hello', 'how r uh ?', 'i m fne uh say']
a=random.choices(m, k=3)
print(a)

['how r uh ?', 'hello', 'hello']


In [6]:
type(m)

list

In [7]:
len(m)

4

In [8]:
b=random.shuffle(m)
print(m)

['hello', 'i m fne uh say', 'how r uh ?', 'hii']


# numpy

In [9]:
import numpy as np

In [10]:
a=np.array([])
b=np.array([1,2,3,4,5])
c=np.array([[12,13,14,15,11], [23,45,56,67,78]])
d=np.array([[1,2,3,4,5], [500,122,233,45,465] , [1,12,34,7,88]])

In [11]:
a


array([], dtype=float64)

In [12]:
a.size

0

In [13]:
type(a)

numpy.ndarray

In [14]:
a.shape

(0,)

In [15]:
a.ndim

1

In [16]:
type(b)

numpy.ndarray

In [17]:
b.ndim

1

In [18]:
b.shape

(5,)

In [19]:
b.size

5

In [20]:
c


array([[12, 13, 14, 15, 11],
       [23, 45, 56, 67, 78]])

In [21]:
c.size

10

In [22]:
c.shape

(2, 5)

In [23]:
c.ndim

2

In [24]:
type(c)

numpy.ndarray

In [25]:
d.size

15

In [26]:
d.shape

(3, 5)

In [27]:
d.ndim

2

In [28]:
type(d)

numpy.ndarray

In [29]:
n=np.array([ [2,3,4,5],[20,10,30,40],[200,300,400,500 ]])


In [30]:
n.shape

(3, 4)

In [31]:
n.size

12

In [32]:
n.ndim

2

In [33]:
type(n)

numpy.ndarray

In [34]:
m=np.array([[11,23],[10,23],[1,22]])

In [35]:
type(m)

numpy.ndarray

In [36]:
type(m)

numpy.ndarray

In [37]:
m.size

6

In [38]:
type(a)

numpy.ndarray

In [39]:
m.shape

(3, 2)

In [40]:
m.ndim

2

# os 

In [41]:
import os 

In [42]:
os.getcwd()

'C:\\Users\\user\\Desktop\\python training\\ancnda dy 1'

In [43]:
os.chdir('C:\\Users\\user\\Desktop\\python training\\day2')

In [44]:
os.getcwd()

'C:\\Users\\user\\Desktop\\python training\\day2'

In [45]:
os.getcwd()

'C:\\Users\\user\\Desktop\\python training\\day2'

In [46]:
import os

In [47]:
os.getcwd()

'C:\\Users\\user\\Desktop\\python training\\day2'

In [48]:
os.chdir('C:\\Users\\user\\Desktop\\python training\\ancnda dy 1')

In [49]:
os.getcwd()

'C:\\Users\\user\\Desktop\\python training\\ancnda dy 1'

In [50]:
os.listdir('C:\\Users\\user\\Desktop\\python training\\ancnda dy 1')

['.ipynb_checkpoints', 'ancnda dy1', 'home practice']

In [51]:
import datetime as dt

In [52]:
a= dt.date.today()

In [53]:
a

datetime.date(2022, 9, 23)

In [54]:
print(a)

2022-09-23


In [55]:
import calendar 

In [56]:
a= print(calendar.calendar(2022))

                                  2022

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
                1  2          1  2  3  4  5  6          1  2  3  4  5  6
 3  4  5  6  7  8  9       7  8  9 10 11 12 13       7  8  9 10 11 12 13
10 11 12 13 14 15 16      14 15 16 17 18 19 20      14 15 16 17 18 19 20
17 18 19 20 21 22 23      21 22 23 24 25 26 27      21 22 23 24 25 26 27
24 25 26 27 28 29 30      28                        28 29 30 31
31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
             1  2  3                         1             1  2  3  4  5
 4  5  6  7  8  9 10       2  3  4  5  6  7  8       6  7  8  9 10 11 12
11 12 13 14 15 16 17       9 10 11 12 13 14 15      13 14 15 16 17 18 19
18 19 20 21 22 23 24      16 17 18 19 20 21 22      20 21 22 23 24 25 26
25 26 27 28 29 30         23 24 

In [57]:
print(calendar.calendar(2022,9))

                                                                                                            2022

                               January                                                                    February                                                                    March
  Monday   Tuesday  Wednesday  Thursday   Friday   Saturday   Sunday         Monday   Tuesday  Wednesday  Thursday   Friday   Saturday   Sunday         Monday   Tuesday  Wednesday  Thursday   Friday   Saturday   Sunday
                                                       1         2                        1         2         3         4         5         6                        1         2         3         4         5         6
     3         4         5         6         7         8         9              7         8         9        10        11        12        13              7         8         9        10        11        12        13
    10        11        12        13        1

In [58]:
c= print(calendar.month(2021, 9))

   September 2021
Mo Tu We Th Fr Sa Su
       1  2  3  4  5
 6  7  8  9 10 11 12
13 14 15 16 17 18 19
20 21 22 23 24 25 26
27 28 29 30



In [59]:
import calendar 

In [60]:
print(calendar.calendar(2022))

                                  2022

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
                1  2          1  2  3  4  5  6          1  2  3  4  5  6
 3  4  5  6  7  8  9       7  8  9 10 11 12 13       7  8  9 10 11 12 13
10 11 12 13 14 15 16      14 15 16 17 18 19 20      14 15 16 17 18 19 20
17 18 19 20 21 22 23      21 22 23 24 25 26 27      21 22 23 24 25 26 27
24 25 26 27 28 29 30      28                        28 29 30 31
31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
             1  2  3                         1             1  2  3  4  5
 4  5  6  7  8  9 10       2  3  4  5  6  7  8       6  7  8  9 10 11 12
11 12 13 14 15 16 17       9 10 11 12 13 14 15      13 14 15 16 17 18 19
18 19 20 21 22 23 24      16 17 18 19 20 21 22      20 21 22 23 24 25 26
25 26 27 28 29 30         23 24 

In [61]:
print(calendar.month(2022,3))

     March 2022
Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6
 7  8  9 10 11 12 13
14 15 16 17 18 19 20
21 22 23 24 25 26 27
28 29 30 31



In [62]:
import datetime as dt

In [63]:
a=print(dt.date.today())

2022-09-23


In [64]:
# Python 3: Fibonacci series up to n
def fib(n):
     a, b = 0, 1
     while a < n:
        print(a, end=' ')
        a, b = b, a+b
     print()
fib(1000)

0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 


# numpy

In [65]:
import numpy as np 


In [66]:
x= np.array([[1,2,3,4], [4,5,6,7] , [8,9,0,1]])

In [67]:
x


array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [8, 9, 0, 1]])

In [68]:
x[0:4,1:4]

array([[2, 3, 4],
       [5, 6, 7],
       [9, 0, 1]])

In [69]:
x[2:,0:2]

array([[8, 9]])

In [70]:
x[2:,2:0]

array([], shape=(1, 0), dtype=int32)

In [71]:
x[1][2:4]

array([6, 7])

In [72]:
x[2][0:2]

array([8, 9])

In [73]:
x*2

array([[ 2,  4,  6,  8],
       [ 8, 10, 12, 14],
       [16, 18,  0,  2]])

In [74]:
x+1

array([[ 2,  3,  4,  5],
       [ 5,  6,  7,  8],
       [ 9, 10,  1,  2]])

In [75]:
x-1

array([[ 0,  1,  2,  3],
       [ 3,  4,  5,  6],
       [ 7,  8, -1,  0]])

In [76]:
list(range(0,51))

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50]

In [77]:
list(range(0,51))


[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50]

In [78]:
np.arange(0,51)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [79]:
np.arange(0,12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [80]:
np.arange(0.5,50,3)

array([ 0.5,  3.5,  6.5,  9.5, 12.5, 15.5, 18.5, 21.5, 24.5, 27.5, 30.5,
       33.5, 36.5, 39.5, 42.5, 45.5, 48.5])

In [81]:
x.argmax()

9

In [82]:
x.argmin()

10

In [83]:
x.sum

<function ndarray.sum>

In [84]:
x.sum()

50

In [85]:
x.sum(axis=1)

array([10, 22, 18])

In [86]:
x.sum(axis=0)

array([13, 16,  9, 12])

# dataframe 

In [89]:
import pandas as pd

In [109]:
z=pd.Series([[1,2,3,4],[4,5,6,7],[8,9,19,1],[2,3,4,5]],index= ['a', 'b','c','d'])

In [110]:
z

a     [1, 2, 3, 4]
b     [4, 5, 6, 7]
c    [8, 9, 19, 1]
d     [2, 3, 4, 5]
dtype: object

In [100]:
z

a     [1, 2, 3, 4]
b     [4, 5, 6, 7]
c    [8, 9, 19, 1]
d     [2, 3, 4, 5]
dtype: object

In [101]:
z

a     [1, 2, 3, 4]
b     [4, 5, 6, 7]
c    [8, 9, 19, 1]
d     [2, 3, 4, 5]
dtype: object

In [96]:
z

a    [1, 2, 3, 4]
b    [4, 5, 6, 7]
c    [8, 9, 0, 1]
d    [2, 3, 4, 5]
dtype: object

In [102]:
x.argmax()

9

In [103]:
x.argmin()

10

In [104]:
x.argmax()

9

In [105]:
x.argmin

<function ndarray.argmin>

In [107]:
x.argmin()

10

In [114]:
z.idxmax

<bound method Series.idxmax of a     [1, 2, 3, 4]
b     [4, 5, 6, 7]
c    [8, 9, 19, 1]
d     [2, 3, 4, 5]
dtype: object>

In [116]:
z.value_counts()

[1, 2, 3, 4]     1
[4, 5, 6, 7]     1
[8, 9, 19, 1]    1
[2, 3, 4, 5]     1
dtype: int64

In [119]:
z.idxmin

<bound method Series.idxmin of a     [1, 2, 3, 4]
b     [4, 5, 6, 7]
c    [8, 9, 19, 1]
d     [2, 3, 4, 5]
dtype: object>

In [120]:
z['a']

[1, 2, 3, 4]

In [121]:
z['d']

[2, 3, 4, 5]

In [122]:
import pandas as pd

In [123]:
import numpy as np 

In [126]:
a=pd.DataFrame([])
b=pd.DataFrame([12,23,34,45,56,21])

In [128]:
a

Empty DataFrame
Columns: []
Index: []

In [129]:
b

0
0  12
1  23
2  34
3  45
4  56
5  21

In [130]:
b[0]

0    12
1    23
2    34
3    45
4    56
5    21
Name: 0, dtype: int64

In [133]:
type (b)

pandas.core.frame.DataFrame

In [142]:
c= pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=['a','b','c'])

In [145]:
c

a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [143]:
c

a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [144]:
type(c)

pandas.core.frame.DataFrame

In [146]:
c

a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [147]:
c['d']= [1,2,3]

In [148]:
c

a  b  c  d
0  1  2  3  1
1  4  5  6  2
2  7  8  9  3

In [151]:
c['e']=c['c']*c['d']

In [152]:
c

a  b  c  d   e
0  1  2  3  1   3
1  4  5  6  2  12
2  7  8  9  3  27

In [153]:
c

a  b  c  d   e
0  1  2  3  1   3
1  4  5  6  2  12
2  7  8  9  3  27

In [154]:
c.head(2)

a  b  c  d   e
0  1  2  3  1   3
1  4  5  6  2  12

In [155]:
c.tail(2)

a  b  c  d   e
1  4  5  6  2  12
2  7  8  9  3  27

In [156]:
a=c['d']>1

In [157]:
a

0    False
1     True
2     True
Name: d, dtype: bool

In [158]:
c[a]

a  b  c  d   e
1  4  5  6  2  12
2  7  8  9  3  27

In [159]:
c['e'].max()

27

In [160]:
c['a'].min()

1

In [164]:
c[['a','b']].head(1)

a  b
0  1  2