import numpy as np


In [1]:
import numpy as np

In [13]:
a=np.array([])
b=np.array([1,2,3,24,56])
c=np.array([[12,34,45],[4,5,7]])
d=np.array([[1,2,3],[1,2,3],[1,2,3]])

In [4]:
a

array([], dtype=float64)

In [7]:
type(a)

numpy.ndarray

In [10]:
a.ndim

1

In [5]:
b

array([ 1,  2,  3, 24, 56])

In [11]:
b.ndim

1

In [19]:
b.size

5

In [8]:
type(b)

numpy.ndarray

In [6]:
c

array([[12, 34, 45],
       [ 4,  5,  7]])

In [20]:
c.shape

(2, 3)

In [9]:
type(c)

numpy.ndarray

In [18]:
c.size

6

In [12]:
c.ndim

2

In [14]:
d


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [15]:
type(d)

numpy.ndarray

In [16]:
d.ndim

2

In [17]:
d.size

9

In [21]:
d.shape

(3, 3)

In [22]:
n=np.array([ [2,3,4,5],[20,10,30,40],[200,300,400,500 ]])

In [23]:
n.shape

(3, 4)